[phases.setup]
nixPkgs = [
  "python313",
  "gcc",
  "pkg-config",
  "stdenv.cc.cc.lib",
  "zlib",
  "libGL",
  "glib",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libXrender",
  "xorg.libxcb",
  "xorg.libXau",
  "xorg.libXdmcp"
]

[start]
cmd = "gunicorn app:app"